services:
  db:
    image: postgres
    volumes:
      - postgres_db_todo:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=flask
      - POSTGRES_USER=flask
      - POSTGRES_PASSWORD=gunicorn
  web:
    image: python-docker
    volumes:
      - todo:/tmp
    environment:
      - DATABASE_URL=postgres://flask:gunicorn@db/flask
    depends_on:
      - db
  nginx:
    image: flask-nginx
    depends_on:
      - web
    ports:
      - "5000:5000"
volumes:
  todo:

  postgres_db_todo:
